name: lms_mobile
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  printing: ^5.11.1

  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/gedung.jpeg
    - assets/images/vector1.png
    - assets/images/logo_tel.png
    - assets/images/indonesia.png
    - assets/images/united-kingdom.png
    - assets/images/gambar_pengumuman.png
    - assets/images/ui_ux.png
    - assets/images/sistem_operasi.png
    - assets/images/notif1.png
    - assets/images/ic_quiz.png
    - assets/images/ic_tugas.png
    - assets/images/ic_speaker.png
    - assets/images/ic_person.png
    - assets/images/no-image.png
    - assets/images/profilku.jpeg
    - assets/images/ic_logout.png
    - assets/images/ic_file_video.png
    - assets/images/ic_interactive_content.png
    - assets/images/ic_url.png
    - assets/images/gembira.png
    - assets/01_Slide-Pengantar-PAA.pdf